# Generated by Django 3.0.14 on 2023-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20230619_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.auctions'),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
