# Generated by Django 3.0.14 on 2023-06-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20230619_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comments',
        ),
    ]
