# Generated by Django 3.0.14 on 2023-06-20 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='bid',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
