# Generated by Django 3.0.14 on 2023-06-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20230620_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
